### ISSUE TITLE
Neighbor Cells Sporadically Not Showing Notes

### ISSUE THREAD

**Issue by tripinva** [bluelinepc/signalcheck#15] opened 2022-07-28 01:39 UTC
I wanted to flag something I noticed since upgrading to my S21FE which I'm not sure if it's always been there or is new.  See the attached screenshot I took this morning.

If you look at the Neighbor Cells in the screenshot link below, you'll see that although PCI 73 appears twice, once for each B2 carrier, the note only appears next to one of them.  I used this as an illustrative example of the issue because you can clearly see where that the row is in the database, but it's somehow not being retrieved or displayed properly in both spots.  In other cases, I've seen all neighbor cells come up with no notes, or selected ones where there isn't a duplicate to easily demonstrate.  But it's sporadic; it only happens sometimes.  I haven't observed a pattern as to when it happens.

Screenshot:  https://imgur.com/a/R0Glm2K

**Device details**
 - Device: Samsung S21FE
 - Android version: 12
 - SignalCheck version: Previous beta prior to 4.713b

**Comment by mikejeep** [comment] 2022-08-02 14:45
Can you send me a copy of your database?

**Comment by tripinva** [comment] 2022-08-03 10:52
I've e-mailed it to you.  Let me know if there's anything else I can provide.

**Comment by mikejeep** [comment] 2023-09-13 20:58
I believe this is related to a SQL query issue I recently discovered. It's on my list, will keep this open.

**Comment by TripEricson** [comment] 2023-09-14 12:35
My S21FE is now usually locked on n25, and doesn't report neighbor cells in NR mode.  I keep it unlocked around the house and around town, so I'll try to keep an eye out for this one as well.

**Comment by TripEricson** [comment] 2023-11-15 17:00
I happened to notice my Samsung A42 still showing this issue over the weekend.

![Screenshot_20231111-064628_SignalCheck Pro](https://github.com/bluelinepc/signalcheck/assets/43734293/09bb8a89-4e56-4877-b02f-6fd45b609a93)

**Comment by mikejeep** [comment] 2024-03-19 12:56
Fix (finally.. hopefully) pending in upcoming beta 4.831b, please test and let me know.

**Comment by TripEricson** [comment] 2024-03-20 12:27
Looking forward to it!  My Verizon phone is the one I see it on most, so I'll test it there.

**Comment by TripEricson** [comment] 2024-03-26 22:52
![Screenshot_20240326-165425_SignalCheck Pro](https://github.com/bluelinepc/signalcheck/assets/43734293/611477dc-5307-4545-9d40-bacef5c4e212)

Hate to be the bearer of bad news, but...

**Comment by mikejeep** [comment] 2024-03-27 02:55
Could you send me a backup of your log database again?

**Comment by TripEricson** [comment] 2024-03-27 13:19
Sent the Verizon file via e-mail.

**Comment by TripEricson** [comment] 2024-03-27 13:45
Something jumps out at me in all three screenshots here.  I'd have to check if this is consistent across the board or coincidental that all three of my screenshots look that way.  But in each case, it's always the first neighbor cell in the list, and that first neighbor cell is on the same EARFCN as the connected cell.  Could it be something about that specific set of conditions causing it to not display?

**Comment by mikejeep** [comment] 2024-06-26 04:44
This bug was hopefully resolved with version 4.834b back on April 9.. any further observations of it?

**Comment by TripEricson** [comment] 2024-06-26 18:58
I'll look at my Verizon phone again this afternoon when I go out for dinner, but I'm pretty sure I've seen it more recently than that.

**Comment by TripEricson** [comment] 2024-06-26 22:33
Well, I was out and about for dinner and I didn't see it happen.  I remember last time I looked for it, I saw it almost right away.  I'll try to take it out again tomorrow or Friday for grocery shopping, but I'm going to tentatively suggest it may be corrected.  If I might ask, what was the fix?

**Comment by mikejeep** [comment] 2024-06-30 18:22
I'll wait to hear back from you, just let me know. I completely overhauled the SQL queries to grab site notes.. the bug was tough to replicate because it was only triggered with certain entries recorded in the sites table in a certain order. A flaw in the code logic that was designed to resolve issues with providers that use multiple PLMNs (like the various options that Sprint/T-Mobile/Clearwire/Shentel/etc have used) could clear the site note string even if the proper note was actually selected, regardless of the PLMN.

**Comment by TripEricson** [comment] 2024-06-30 20:11
So, glad you posted this, it was a good reminder.  I was out and about, and watched it like a hawk the rest of the outing, which was 25-30 minutes.  It's significantly better than it was.  I only saw a single blank row pop up once, when this used to appear repeatedly and frequently.  I'm willing to say you've got it.  Thanks so much!

(By the way, the other ticket you closed about inactive SIMs, I noticed my Verizon phone is now showing me when it's got no Verizon service and is connected to other carriers for 911 purposes.  I'd say you've got that one too.)

**Closed as completed** 2024-07-12 05:43 UTC
Labels: bug, question
